// <auto-generated />
using EF7JsonColumn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF7JsonColumn.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221230225414_initalCreate")]
    partial class initalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF7JsonColumn.SuperHero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("EF7JsonColumn.SuperHero", b =>
                {
                    b.OwnsOne("EF7JsonColumn.HeroDetails", "Details", b1 =>
                        {
                            b1.Property<int>("SuperHeroid")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SuperHeroid");

                            b1.ToTable("Heroes");

                            b1.ToJson("Details");

                            b1.WithOwner()
                                .HasForeignKey("SuperHeroid");
                        });

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
